version: "3"

services:
  web:
    build: .
    command: rails server -b 0.0.0.0 -p 4000
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      SECRET_KEY_BASE: mysecretkey
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'root'
      POSTGRES_HOST: db # Use the service name defined below
    volumes:
      - .:/app

  db:
    image: kartoza/postgis:16-3.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 'root'
      POSTGRES_DB: vtbMaps_development
      POSTGRES_MULTIPLE_EXTENSIONS: postgis
    ports:
      - "5432:5432"

volumes:
  db_data:
